#!/bin/bash
if [ ! -f "his-config.php" ]; then
    echo ""
    echo "  Paste your his-config.php file into this folder before continuing."
    echo ""
    echo "  his-config.php is generated by your HIS Web Interface."
    echo "  Install the Web Interface before installing the Job Server."
    echo ""
    echo "  In your HIS Web Interface, hit the Map icon, followed by the \"Add Server\" icon,"
    echo "  to find the content you need to paste into your his-config.php file."
    echo ""
    exit;
fi

if [ ! -f "launch_job_cluster.sh" ]; then
    echo ""
    echo "  Paste your launch_job_cluster.sh file into this folder before continuing."
    echo ""
    echo "  launch_job_cluster.sh is generated by your HIS Web Interface."
    echo "  Install the Web Interface before installing the Job Server."
    echo ""
    echo "  In your HIS Web Interface, hit the Map icon, followed by the \"Add Server\" icon,"
    echo "  to find the content you need to paste into your auth.xml file."
    echo ""
    exit;
fi

if [ ! -f "auth.xml" ]; then
    echo ""
    echo "  Paste your auth.xml file into this folder before continuing."
    echo ""
    echo "  auth.xml is generated by your HIS Web Interface."
    echo "  Install the Web Interface before installing the Job Server."
    echo ""
    echo "  In your HIS Web Interface, hit the Map icon, followed by the \"Add Server\" icon,"
    echo "  to find the content you need to paste into your auth.xml file."
    echo ""
    exit;
fi


chmod +x *.sh

# DOWNLOAD HIS
if [ ! -d his ]; then
    wget --no-check-certificate --output-document=his.tar "https://humanintelligencesystem.com/version/?get=current&type=tar"
    tar xvf his.tar
fi

echo "  HIS Server setup complete"
echo ""
echo "Executing:"
echo ""
echo "    ./launch_job_cluster.sh"
echo ""
echo "Launching server instances..."
echo ""
echo ""

chmod +x launch_job_cluster.sh
./launch_job_cluster.sh

