Set oShell = CreateObject("WScript.Shell")
strHomeFolder = oShell.ExpandEnvironmentStrings("%USERPROFILE%")

Dim filesys
Set filesys = CreateObject("Scripting.FileSystemObject") 
Set oShell = CreateObject("WScript.Shell")

' OBSERVE IF HIS-CONFIG.PHP EXISTS
If Not filesys.FileExists("his-config.php") Then
	MsgBox("Paste your his-config.php file into this folder before continuing."+vbCr+vbCr+"his-config.php is generated by your HIS Web Interface.  Install the Web Interface before installing the Job Server."+vbCr+vbCr+"In your HIS Web Interface, hit the Map icon, followed by the ""Add Server"" icon, to find the content you need to paste into your his-config.php file.")
	Wscript.quit()
End If

' OBSERVE IF launch_job_cluster.vbs EXISTS
If Not filesys.FileExists("launch_job_cluster.vbs") Then
	MsgBox("Paste your launch_job_cluster.vbs file into this folder before continuing."+vbCr+vbCr+"launch_job_cluster.vbs is generated by your HIS Web Interface.  Install the Web Interface before installing the Job Server."+vbCr+vbCr+"In your HIS Web Interface, hit the Map icon, followed by the ""Add Server"" icon, to find the content you need to paste into your launch_job_cluster.vbs file.")
	Wscript.quit()
End If

' OBSERVE IF auth.xml EXISTS
If Not filesys.FileExists("auth.xml") Then
	MsgBox("Paste your auth.xml file into this folder before continuing."+vbCr+vbCr+"auth.xml is generated by your HIS Web Interface.  Install the Web Interface before installing the Job Server."+vbCr+vbCr+"In your HIS Web Interface, hit the Map icon, followed by the ""Add Server"" icon, to find the content you need to paste into your auth.xml file.")
	Wscript.quit()
End If


' DOWNLOAD HIS
If Not filesys.FolderExists("his") Then
	oShell.Run "wget\wget.exe --no-check-certificate --output-document=his.zip https://humanintelligencesystem.com/version/?get=current",1,True
	oShell.Run "7zip\7za.exe x -y his.zip",1,True
End If

' DOWNLOAD SERVERBINS-WIN
If Not filesys.FolderExists("serverbins-win") Then
	oShell.Run "wget\wget.exe --no-check-certificate --output-document=serverbins-win.zip https://humanintelligencesystem.com/version/?dl=serverbins-win",1,True
	oShell.Run "7zip\7za.exe x -y serverbins-win.zip",1,True
End If

MsgBox "Setup complete",0,"Installation complete"

x=MsgBox("Run HIS Server now?"+vbCrLf+vbCrLf+"  (launch_job_cluster.vbs will be run)",1)
If x = 2 Then
	Wscript.quit()
Else
	oShell.Run "launch_job_cluster.vbs",1,true
End If



