  CREATE TABLE "DBNAME"."JOB_NEW" 
   (	"ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(100 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."JOB_ID_USER" 
   (	"ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(100 BYTE) DEFAULT 'undefined', 
	"ID_STATUS" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"DT_CREATED" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"DT_MODIFIED" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"DT_DONE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_RQDATA" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_RESPONSE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_OUTPUT" VARCHAR2(50 BYTE) DEFAULT 'undefined',
	"STR_AD" VARCHAR2(50 BYTE) DEFAULT 'undefined',
	"INT_TRY" VARCHAR2(7 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."MATCH_CUSTOM" 
   (	"ID_EXPR" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"IDX_KEY" VARCHAR2(40 BYTE) DEFAULT 'undefined', 
	"STR_TXT" VARCHAR2(40 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."MATCH_ENTRY" 
   (	"ID_EXPR" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"IDX_ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID_ENTRY_TYPE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID_ENTRY_SUBTYPE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"INT_ORDER" VARCHAR2(11 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."ME_SETTING" 
   (	"ID_ME" VARCHAR2(120 BYTE) DEFAULT 'undefined', 
	"NAME" VARCHAR2(255 BYTE) DEFAULT 'undefined', 
	"STR_VALUE" VARCHAR2(500 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."PH_CHILD" 
   (	"ID_CHILD_JOB" VARCHAR2(100 BYTE) DEFAULT 'undefined', 
	"ID_PARENT_JOB" VARCHAR2(100 BYTE) DEFAULT 'undefined', 
	"PLACEHOLDER" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."PH_PARENT" 
   (	"ID_PARENT_JOB" VARCHAR2(100 BYTE) DEFAULT 'undefined', 
	"ID_CHILD_JOB" VARCHAR2(100 BYTE) DEFAULT 'undefined', 
	"PLACEHOLDER" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HFP_VCS" 
   (	"ID_HF_PARAMETER" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID_CONSTRAINT_TYPE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_CONSTRAINT_TEXT" VARCHAR2(300 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HF_FILE" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_FILE" VARCHAR2(600 BYTE) DEFAULT 'undefined', 
	"STR_TARGETFILE" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HF_KILL" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_NAME" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HF_NODE_FILTER" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_FILTER" VARCHAR2(255 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "DBNAME"."HF_PARAMETER" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"KEYWORD" VARCHAR2(200 BYTE) DEFAULT '', 
	"PARAMETER_NAME" VARCHAR2(200 BYTE) DEFAULT '', 
	"STR_DEFAULT_VALUE" VARCHAR2(50 BYTE) DEFAULT '', 
	"INT_PRESERVE_ENCODE" VARCHAR2(2 BYTE) DEFAULT '0',
	"INT_MANDATORY" VARCHAR2(1 BYTE) DEFAULT '0',
	"INT_IMMUTABLE" VARCHAR2(1 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HF_TAG" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_TAG" VARCHAR2(50 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HF_ID_USER" 
   (	"ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"NAME" VARCHAR2(300 BYTE) DEFAULT 'undefined', 
	"STR_EXPRESSION" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID_CONDITION" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_CACHE_OUT_XML" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_CACHE_OUT_CXML" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_CACHE_APPROVED" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_CACHE_LATEST" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_CACHE_AD" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"ID_MIME_TYPE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"INT_WS" VARCHAR2(2 BYTE) DEFAULT '0', 
	"INT_WAIT" VARCHAR2(1 BYTE) DEFAULT '0', 
	"INT_CLEANUP" VARCHAR2(1 BYTE) DEFAULT '1', 
	"INT_MAXRUNTIME" VARCHAR2(8 BYTE) DEFAULT '0',
	"INT_MTF" VARCHAR2(8 BYTE) DEFAULT '1',
	"INT_RETRY_COUNT" VARCHAR2(8 BYTE) DEFAULT '0',
	"STR_FASTRESPONSE" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."STRINGS" 
   (	"ID" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"VAL" VARCHAR2(600 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."USER_SERVER" 
   (	"ID_USER" VARCHAR2(40 BYTE) DEFAULT 'undefined', 
	"NAME" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"LAST_PING" VARCHAR2(20 BYTE) DEFAULT 'undefined', 
	"FORCE_RESTART" VARCHAR2(2 BYTE) DEFAULT '0', 
	"STR_LOG" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"IP_ADDRESS" VARCHAR2(25 BYTE) DEFAULT 'undefined', 
	"ID_SK" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"INT_ROUTABLE" VARCHAR2(1 BYTE) DEFAULT '0',
	"IS_BUSY" VARCHAR2(1 BYTE) DEFAULT '0',
	"INT_ONLINE" VARCHAR2(1 BYTE) DEFAULT '1',
	"SOFTWARE_VERSION" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."USER_ID_USER" 
   (	"ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"USER_NAME" VARCHAR2(250 BYTE) DEFAULT '', 
	"EMAIL" VARCHAR2(100 BYTE) DEFAULT '', 
	"PW" VARCHAR2(50 BYTE) DEFAULT '', 
	"SECRET" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"LANG" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."USER_USER_NAME" 
   (	"USER_NAME" VARCHAR2(250 BYTE) DEFAULT '', 
	"EMAIL" VARCHAR2(100 BYTE) DEFAULT '', 
	"PW" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"SECRET" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"LANG" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "DBNAME"."HF_FLAG"
   (	"ID_HF" VARCHAR2(100 BYTE) DEFAULT 'undefined', 
	"flag" VARCHAR2(50 BYTE) DEFAULT 'undefined'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE UNIQUE INDEX "DBNAME"."PKEY_JOB_NEW" ON "DBNAME"."JOB_NEW" ("ID_USER", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_JOB_ID_USER" ON "DBNAME"."JOB_ID_USER" ("ID_USER", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_MATCH_CUSTOM" ON "DBNAME"."MATCH_CUSTOM" ("ID_EXPR", "IDX_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_MATCH_ENTRY" ON "DBNAME"."MATCH_ENTRY" ("ID_EXPR", "IDX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_ME_SETTING" ON "DBNAME"."ME_SETTING" ("ID_ME", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_PH_CHILD" ON "DBNAME"."PH_CHILD" ("ID_CHILD_JOB", "ID_PARENT_JOB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_PH_PARENT" ON "DBNAME"."PH_PARENT" ("ID_PARENT_JOB", "ID_CHILD_JOB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HFP_VCS" ON "DBNAME"."HFP_VCS" ("ID_HF_PARAMETER", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_FILE" ON "DBNAME"."HF_FILE" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_KILL" ON "DBNAME"."HF_KILL" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_NODE_FILTER" ON "DBNAME"."HF_NODE_FILTER" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_PARAMETER" ON "DBNAME"."HF_PARAMETER" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_TAG" ON "DBNAME"."HF_TAG" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_ID_USER" ON "DBNAME"."HF_ID_USER" ("ID_USER", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_STRINGS" ON "DBNAME"."STRINGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_USER_SERVER" ON "DBNAME"."USER_SERVER" ("ID_USER", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_USER_ID_USER" ON "DBNAME"."USER_ID_USER" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_USER_USER_NAME" ON "DBNAME"."USER_USER_NAME" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."JOB_NEW" ADD CONSTRAINT "PKEY_JOB_NEW" PRIMARY KEY ("ID_USER", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."JOB_NEW" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_NEW" MODIFY ("ID_USER" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."JOB_ID_USER" ADD CONSTRAINT "PKEY_JOB_ID_USER" PRIMARY KEY ("ID_USER", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("INT_TRY" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("STR_AD" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("STR_OUTPUT" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("STR_RESPONSE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("STR_RQDATA" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("DT_DONE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("DT_MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("DT_CREATED" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("ID_HF" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_ID_USER" MODIFY ("ID_USER" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."MATCH_CUSTOM" ADD CONSTRAINT "PKKEY_MATCH_CUSTOM" PRIMARY KEY ("ID_EXPR", "IDX_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."MATCH_CUSTOM" MODIFY ("STR_TXT" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."MATCH_CUSTOM" MODIFY ("IDX_KEY" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."MATCH_CUSTOM" MODIFY ("ID_EXPR" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."MATCH_ENTRY" ADD CONSTRAINT "PKEY_MATCH_ENTRY" PRIMARY KEY ("ID_EXPR", "IDX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."MATCH_ENTRY" MODIFY ("INT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."MATCH_ENTRY" MODIFY ("ID_ENTRY_SUBTYPE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."MATCH_ENTRY" MODIFY ("ID_ENTRY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."MATCH_ENTRY" MODIFY ("IDX_ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."MATCH_ENTRY" MODIFY ("ID_EXPR" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."ME_SETTING" ADD CONSTRAINT "PKEY_ME_SETTING" PRIMARY KEY ("ID_ME", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."ME_SETTING" MODIFY ("STR_VALUE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."ME_SETTING" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."ME_SETTING" MODIFY ("ID_ME" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."PH_CHILD" ADD CONSTRAINT "PKEY_PH_CHILD" PRIMARY KEY ("ID_CHILD_JOB", "ID_PARENT_JOB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."PH_CHILD" MODIFY ("PLACEHOLDER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."PH_CHILD" MODIFY ("ID_PARENT_JOB" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."PH_CHILD" MODIFY ("ID_CHILD_JOB" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."PH_PARENT" ADD CONSTRAINT "PKEY_PH_PARENT" PRIMARY KEY ("ID_PARENT_JOB", "ID_CHILD_JOB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."PH_PARENT" MODIFY ("PLACEHOLDER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."PH_PARENT" MODIFY ("ID_CHILD_JOB" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."PH_PARENT" MODIFY ("ID_PARENT_JOB" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HFP_VCS" ADD CONSTRAINT "PKEY_HFP_VCS" PRIMARY KEY ("ID_HF_PARAMETER", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HFP_VCS" MODIFY ("STR_CONSTRAINT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HFP_VCS" MODIFY ("ID_CONSTRAINT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HFP_VCS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HFP_VCS" MODIFY ("ID_HF_PARAMETER" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HF_FILE" ADD CONSTRAINT "PKEY_HF_FILE" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_FILE" MODIFY ("STR_TARGETFILE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_FILE" MODIFY ("STR_FILE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_FILE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_FILE" MODIFY ("ID_HF" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HF_KILL" ADD CONSTRAINT "PKEY_HF_KILL" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_KILL" MODIFY ("STR_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_KILL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_KILL" MODIFY ("ID_HF" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HF_NODE_FILTER" ADD CONSTRAINT "PKEY_HF_NODE_FILTER" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_NODE_FILTER" MODIFY ("STR_FILTER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_NODE_FILTER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_NODE_FILTER" MODIFY ("ID_HF" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HF_PARAMETER" ADD CONSTRAINT "PKEY_HF_PARAMETER" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("INT_IMMUTABLE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("INT_MANDATORY" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("INT_PRESERVE_ENCODE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("STR_DEFAULT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("PARAMETER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("KEYWORD" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_PARAMETER" MODIFY ("ID_HF" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HF_TAG" ADD CONSTRAINT "PKEY_HF_TAG" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_TAG" MODIFY ("STR_TAG" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_TAG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_TAG" MODIFY ("ID_HF" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("ID_MIME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_CACHE_OUT_CXML" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_CACHE_OUT_XML" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_CACHE_APPROVED" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_CACHE_LATEST" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_FASTRESPONSE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_CACHE_AD" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("ID_CONDITION" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("STR_EXPRESSION" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "DBNAME"."HF_ID_USER" ADD CONSTRAINT "PKEY_HF_ID_USER" PRIMARY KEY ("ID_USER", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("INT_MTF" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("INT_RETRY_COUNT" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("INT_MAXRUNTIME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("INT_WAIT" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("INT_CLEANUP" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_ID_USER" MODIFY ("INT_WS" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."STRINGS" ADD CONSTRAINT "PKEY_STRINGS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."STRINGS" MODIFY ("VAL" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."STRINGS" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."USER_SERVER" ADD CONSTRAINT "PKEY_USER_SERVER" PRIMARY KEY ("ID_USER", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("IP_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("ID_SK" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("INT_ROUTABLE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("SOFTWARE_VERSION" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("IS_BUSY" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("INT_ONLINE" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("STR_LOG" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("FORCE_RESTART" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("LAST_PING" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER" MODIFY ("ID_USER" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."USER_ID_USER" ADD CONSTRAINT "PKEY_USER_ID_USER" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."USER_ID_USER" MODIFY ("LANG" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_ID_USER" MODIFY ("SECRET" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_ID_USER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_ID_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_ID_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_ID_USER" MODIFY ("ID_USER" NOT NULL ENABLE);

  ALTER TABLE "DBNAME"."USER_USER_NAME" ADD CONSTRAINT "PKEY_USER_USER_NAME" PRIMARY KEY ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."USER_USER_NAME" MODIFY ("LANG" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_USER_NAME" MODIFY ("SECRET" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_USER_NAME" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_USER_NAME" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_USER_NAME" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_USER_NAME" MODIFY ("USER_NAME" NOT NULL ENABLE);














  CREATE TABLE "DBNAME"."HF_RESOURCE" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID" VARCHAR2(50 BYTE) DEFAULT '', 
	"STR_LOCATION" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"STR_FILENAME" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_RESOURCE" ON "DBNAME"."HF_RESOURCE" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."HF_RESOURCE" ADD CONSTRAINT "PKEY_HF_RESOURCE" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_RESOURCE" MODIFY ("STR_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HF_RESOURCE" MODIFY ("STR_FILENAME" NOT NULL ENABLE);



  CREATE TABLE "DBNAME"."USER_INHERIT" 
   (	"ID_USER" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID_HF" VARCHAR2(50 BYTE) DEFAULT '', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_USER_INHERIT" ON "DBNAME"."USER_INHERIT" ("ID_USER", "ID_HF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."USER_INHERIT" ADD CONSTRAINT "PKEY_USER_INHERIT" PRIMARY KEY ("ID_USER", "ID_HF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;



  CREATE TABLE "DBNAME"."HF_SYSTEM_KIND" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID_SK" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_SYSTEM_KIND" ON "DBNAME"."HF_SYSTEM_KIND" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."HF_SYSTEM_KIND" ADD CONSTRAINT "PKEY_HF_SYSTEM_KIND" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_SYSTEM_KIND" MODIFY ("ID_SK" NOT NULL ENABLE);


  CREATE TABLE "DBNAME"."HFR_SYSTEM_KIND" 
   (	"ID_RESOURCE" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID_SK" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HFR_SYSTEM_KIND" ON "DBNAME"."HFR_SYSTEM_KIND" ("ID_RESOURCE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."HFR_SYSTEM_KIND" ADD CONSTRAINT "PKEY_HFR_SYSTEM_KIND" PRIMARY KEY ("ID_RESOURCE", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HFR_SYSTEM_KIND" MODIFY ("ID_SK" NOT NULL ENABLE);





  
  
  CREATE TABLE "DBNAME"."USER_SYSTEM_KIND" 
   (	"ID_USER" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID" VARCHAR2(50 BYTE) DEFAULT '', 
	"NAME" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
	"DETECTION_TEXT" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_USER_SYSTEM_KIND" ON "DBNAME"."USER_SYSTEM_KIND" ("ID_USER", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."USER_SYSTEM_KIND" ADD CONSTRAINT "PKEY_USER_SYSTEM_KIND" PRIMARY KEY ("ID_USER", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."USER_SYSTEM_KIND" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SYSTEM_KIND" MODIFY ("DETECTION_TEXT" NOT NULL ENABLE);

  
  
  
  

  CREATE TABLE "DBNAME"."HF_INHERIT" 
   (	"ID_HF" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID" VARCHAR2(50 BYTE) DEFAULT '', 
	"ID_INHERIT" VARCHAR2(50 BYTE) DEFAULT 'undefined', 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HF_INHERIT" ON "DBNAME"."HF_INHERIT" ("ID_HF", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."HF_INHERIT" ADD CONSTRAINT "PKEY_HF_INHERIT" PRIMARY KEY ("ID_HF", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HF_INHERIT" MODIFY ("ID_INHERIT" NOT NULL ENABLE);



  CREATE TABLE "DBNAME"."SYS_SETTING"
   (    "CATEGORY" VARCHAR2(50 BYTE) DEFAULT '',
        "PARAM" VARCHAR2(50 BYTE) DEFAULT '',
        "VAL" VARCHAR2(50 BYTE) DEFAULT 'undefined',
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_SYS_SETTING" ON "DBNAME"."SYS_SETTING" ("CATEGORY", "PARAM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."SYS_SETTING" ADD CONSTRAINT "PKEY_SYS_SETTING" PRIMARY KEY ("CATEGORY", "PARAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."SYS_SETTING" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."SYS_SETTING" MODIFY ("PARAM" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."SYS_SETTING" MODIFY ("VAL" NOT NULL ENABLE);

  
  



  CREATE TABLE "DBNAME"."USER_SERVER_SERVICE"
   (    "ID_USER_SERVER" VARCHAR2(50 BYTE) DEFAULT 'undefined',
        "SERVICE_NAME" VARCHAR2(50 BYTE) DEFAULT 'undefined',
        "SERVICE_ENABLED" VARCHAR2(1 BYTE) DEFAULT '0',
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_USER_SERVER_SERVICE" ON "DBNAME"."USER_SERVER_SERVICE" ("ID_USER_SERVER", "SERVICE_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."USER_SERVER_SERVICE" ADD CONSTRAINT "PKEY_USER_SERVER_SERVICE" PRIMARY KEY ("ID_USER_SERVER", "SERVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."USER_SERVER_SERVICE" MODIFY ("ID_USER_SERVER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER_SERVICE" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."USER_SERVER_SERVICE" MODIFY ("SERVICE_ENABLED" NOT NULL ENABLE);
  



  CREATE TABLE "DBNAME"."HFP_HF"
   (    "PARAMETER_NAME" VARCHAR2(100 BYTE) DEFAULT 'undefined',
        "ID_HF" VARCHAR2(50 BYTE) DEFAULT 'undefined',
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_HFP_HF" ON "DBNAME"."HFP_HF" ("PARAMETER_NAME", "ID_HF")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."HFP_HF" ADD CONSTRAINT "PKEY_HFP_HF" PRIMARY KEY ("PARAMETER_NAME", "ID_HF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."HFP_HF" MODIFY ("PARAMETER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."HFP_HF" MODIFY ("ID_HF" NOT NULL ENABLE);


  CREATE TABLE "DBNAME"."ASSIGN_HF"
   (    "ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined',
        "HF_SERVER" VARCHAR2(100 BYTE) DEFAULT 'undefined',
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_ASSIGN_HF" ON "DBNAME"."ASSIGN_HF" ("ID_USER", "HF_SERVER")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."ASSIGN_HF" ADD CONSTRAINT "PKEY_ASSIGN_HF" PRIMARY KEY ("ID_USER", "HF_SERVER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."ASSIGN_HF" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."ASSIGN_HF" MODIFY ("HF_SERVER" NOT NULL ENABLE);


  CREATE TABLE "DBNAME"."ASSIGN_SERVER"
   (    "ID_USER" VARCHAR2(50 BYTE) DEFAULT 'undefined',
        "SERVER_HF" VARCHAR2(100 BYTE) DEFAULT 'undefined',
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_ASSIGN_SERVER" ON "DBNAME"."ASSIGN_SERVER" ("ID_USER", "SERVER_HF")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."ASSIGN_SERVER" ADD CONSTRAINT "PKEY_ASSIGN_SERVER" PRIMARY KEY ("ID_USER", "SERVER_HF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."ASSIGN_SERVER" MODIFY ("ID_USER" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."ASSIGN_SERVER" MODIFY ("SERVER_HF" NOT NULL ENABLE);



  CREATE TABLE "DBNAME"."JOB_FLAG"
   (    "ID_JOB" VARCHAR2(100 BYTE) DEFAULT 'undefined',
        "FLAG" VARCHAR2(50 BYTE) DEFAULT 'undefined',
        "STATUS" VARCHAR2(100 BYTE) DEFAULT 'undefined',
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "DBNAME"."PKEY_JOB_FLAG" ON "DBNAME"."JOB_FLAG" ("ID_JOB", "FLAG")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  ALTER TABLE "DBNAME"."JOB_FLAG" ADD CONSTRAINT "PKEY_JOB_FLAG" PRIMARY KEY ("ID_JOB", "FLAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBNAME"."JOB_FLAG" MODIFY ("ID_JOB" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_FLAG" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DBNAME"."JOB_FLAG" MODIFY ("FLAG" NOT NULL ENABLE);

